databases:
  - name: alrahma-database
    plan: free

services:
  - type: web
    name: alrahma-backend
    plan: free
    buildCommand: dotnet publish -c Release -o output
    startCommand: dotnet output/AlRahmaBackend.dll

  - type: web
    name: alrahma-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: dist